task: llm-sft
base_model: nvidia/Llama3-ChatQA-1.5-8B
project_name: HPCBot-FT-Llama-3-nvidia-8B-400-2-with-context
log: wandb
backend: local

data:
  path: /home/btrungvo/workspace/HPCBot/data/train/with_golden_context
  train_split: train
  valid_split: null
  chat_template: null
  column_mapping:
    text_column: text

params:
  block_size: 1024
  model_max_length: 8192
  epochs: 400
  batch_size: 2
  lr: 1e-5
  peft: true
  quantization: null
  target_modules: all-linear
  padding: right
  optimizer: paged_adamw_8bit
  scheduler: cosine
  gradient_accumulation: 8
  mixed_precision: bf16
